var annotated_dup =
[
    [ "_MenuItem", "struct___menu_item.html", "struct___menu_item" ],
    [ "Arch", "class_arch.html", "class_arch" ],
    [ "Boulder", "class_boulder.html", "class_boulder" ],
    [ "Boundary", "class_boundary.html", "class_boundary" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "DynamicObject", "class_dynamic_object.html", "class_dynamic_object" ],
    [ "Environment", "class_environment.html", "class_environment" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "Goal", "class_goal.html", "class_goal" ],
    [ "Hero", "class_hero.html", "class_hero" ],
    [ "KinematicObject", "class_kinematic_object.html", "class_kinematic_object" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "MovingPlatform", "class_moving_platform.html", "class_moving_platform" ],
    [ "Obj", "class_obj.html", "class_obj" ],
    [ "ObjGPUData", "class_obj_g_p_u_data.html", "class_obj_g_p_u_data" ],
    [ "ObjGPUDataStore", "class_obj_g_p_u_data_store.html", "class_obj_g_p_u_data_store" ],
    [ "PhysicsObject", "class_physics_object.html", "class_physics_object" ],
    [ "Platform", "class_platform.html", "class_platform" ],
    [ "Ramp", "class_ramp.html", "class_ramp" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "ShaderStore", "class_shader_store.html", "class_shader_store" ],
    [ "Skybox", "class_skybox.html", "class_skybox" ],
    [ "Sound", "class_sound.html", "class_sound" ],
    [ "SoundStore", "class_sound_store.html", "class_sound_store" ],
    [ "Spear", "class_spear.html", "class_spear" ],
    [ "Spikes", "class_spikes.html", "class_spikes" ],
    [ "Stage", "class_stage.html", "class_stage" ],
    [ "StageLoader", "class_stage_loader.html", "class_stage_loader" ],
    [ "StandardObject", "class_standard_object.html", "class_standard_object" ],
    [ "StaticObject", "class_static_object.html", "class_static_object" ],
    [ "Surface", "class_surface.html", "class_surface" ],
    [ "Wall", "class_wall.html", "class_wall" ]
];